### ISSUE TITLE
SE Graal fails to start when reactive Config used

### ISSUE THREAD

**Issue by pfmackin** [tomas-langer/helidon-conference#11]
Add reactive config support, per step 5, build the Graal image and run it.  Startup fails as follows:

Exception in thread "main" java.lang.UnsatisfiedLinkError: sun.nio.fs.LinuxWatchService.inotifyInit()I [symbol: Java_sun_nio_fs_LinuxWatchService_inotifyInit or Java_sun_nio_fs_LinuxWatchService_inotifyInit__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)

...

	at io.helidon.config.Config.onChange(Config.java:990)
	at io.helidon.examples.quickstart.se.GreetService.<init>(GreetService.java:76)

**Comment by tomas-langer** [comment]
This seems to be some graal native-image issue, will investigate.

**Comment by tomas-langer** [comment]
Fixed with Helidon 1.2.1
