### ISSUE TITLE
cant find security.providers in conference-se application.yaml file

### ISSUE THREAD

**Issue by ghost** [tomas-langer/helidon-conference#3]
If I use the configuration approach for the conference-se project with security enabled, it fails while loading the security info from the application.yaml file. The following stack trace is received while running java -jar :
[DEBUG] (main) Using Console logging
2019.04.22 15:46:03 INFO io.helidon.tracing.zipkin.ZipkinTracerBuilder Thread[main,5,main]: Creating Zipkin Tracer for 'helidon-se' configured with: http://127.0.0.1:9411/api/v2/spans
Exception in thread "main" io.helidon.config.MissingValueException: Requested value for configuration key 'providers' is not present in the configuration.
        at io.helidon.config.MissingValueException.create(MissingValueException.java:44)
        at io.helidon.config.ConfigValue.lambda$get$0(ConfigValue.java:109)
        at java.util.Optional.orElseThrow(Unknown Source)
        at io.helidon.config.ConfigValue.get(ConfigValue.java:109)
        at io.helidon.security.Security$Builder.fromConfig(Security.java:843)
        at io.helidon.security.Security$Builder.config(Security.java:798)
        at io.helidon.security.Security.create(Security.java:186)
        at io.helidon.examples.conference.se.Main.setupSecurity(Main.java:117)
        at io.helidon.examples.conference.se.Main.main(Main.java:96)

**Comment by ghost** [comment]
This is the application.yaml file(its exactly the same, no changes made) :

app:
  greeting: "Hello"

health:
  exclude: "heapMemory"

tracing:
  service: "helidon-se"
  protocol: "http"

server:
  port: 8080
  host: 0.0.0.0

security:
  provider-policy:
    type: "COMPOSITE"
    authentication:
      - name: "http-signatures"
        flag: "OPTIONAL"
      - name: "http-basic-auth"
  providers:
    - abac:
    - http-signatures:
        optional: true
        sign-headers:
          - method: "get"
            always: ["date", "(request-target)", "host"]
            if-present: []
        inbound.keys:
          - key-id: "helidon-mp"
            principal-name: "MP Service"
            principal-type: "SERVICE"
            hmac.secret: "badIdeaClearTextPassword!"
    - http-basic-auth:
        users:
          - login: "jack"
            password: "jackIsGreat"
            roles: ["admin"]
          - login: "jill"
            password: "jillToo"
            roles: ["user"]
  web-server:
    paths:
      - path: "/greet/greeting[/{*}]"
        authenticate: true
        roles-allowed: ["admin"]
      - path: "/greet/jack"
        authenticate: true

**Comment by tomas-langer** [comment]
The problem was that we were missing `config.get("security")`. I have updated the source code and added a required dependency.
The master now contains a version that will work by just uncommenting the correct line (and commeting out the programmatic approach).
