### ISSUE TITLE
mvn clean install of helidon-quickstart-mp fails

### ISSUE THREAD

**Issue by pfmackin** [tomas-langer/helidon-conference#7]
Clone the rep and do mvn clean install of the helidon-quickstart-mp fails:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.578 sec <<< FAILURE! - in io.helidon.examples.quickstart.mp.MainTest
io.helidon.examples.quickstart.mp.MainTest  Time elapsed: 1.577 sec  <<< ERROR!
org.jboss.weld.exceptions.DeploymentException: Requested value for configuration key 'app.greeting' is not present in the configuration.
	at io.helidon.examples.quickstart.mp.MainTest.startTheServer(MainTest.java:39)
Caused by: io.helidon.config.MissingValueException: Requested value for configuration key 'app.greeting' is not present in the configuration.
	at io.helidon.examples.quickstart.mp.MainTest.startTheServer(MainTest.java:39)

This is due to having microprofile-config.properties in the test resources.  Even after this is fixed the test fails due to issue #6

**Comment by tomas-langer** [comment]
This is now fixed. Both applications can be built and run from respective module directory.
