### ISSUE TITLE
SE Graal fails to start when HTTP Client used

### ISSUE THREAD

**Issue by pfmackin** [tomas-langer/helidon-conference#9]
in SE demo, I added HTTP client, per step 8 instructions.  I can build the Graal image but it fails when starting.  I starts fine outside of docker/graal (i.e. java -jar target/helidon-quickstart-se.jar)

~/helidon-quickstart-se/helidon-quickstart-se> docker run --rm -p 8080:8080 helidon-quickstart-se-native:latest
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:86)
	at io.helidon.examples.quickstart.se.GreetService.<init>(GreetService.java:79)
	at io.helidon.examples.quickstart.se.Main.createRouting(Main.java:111)
	at io.helidon.examples.quickstart.se.Main.startServer(Main.java:80)
	at io.helidon.examples.quickstart.se.Main.main(Main.java:56)
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
	at java.lang.Class.forName(DynamicHub.java:1131)
	at javax.ws.rs.client.FactoryFinder.newInstance(FactoryFinder.java:87)
	at javax.ws.rs.client.FactoryFinder.find(FactoryFinder.java:185)
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:70)
	... 4 more

**Comment by tomas-langer** [comment]
This is a known issue and will not work for now - this is caused by injection in Jersey.
